In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
data = np.loadtxt(os.path.join("Data","Print_13_v2_PCG_RV.txt"))

In [3]:
x,y = data[:,0],data[:,1]

In [11]:
%matplotlib
plt.plot(x,y)

Using matplotlib backend: TkAgg


C:\Users\adity\miniconda3\envs\Streamlit-Dev\lib\site-packages\ipykernel\eventloops.py:256: RuntimeWarning: coroutine 'Kernel.do_one_iteration' was never awaited
  self.func()
C:\Users\adity\miniconda3\envs\Streamlit-Dev\lib\site-packages\ipykernel\eventloops.py:256: RuntimeWarning: coroutine 'Kernel.do_one_iteration' was never awaited
  self.func()
C:\Users\adity\miniconda3\envs\Streamlit-Dev\lib\site-packages\ipykernel\eventloops.py:256: RuntimeWarning: coroutine 'Kernel.do_one_iteration' was never awaited
  self.func()
C:\Users\adity\miniconda3\envs\Streamlit-Dev\lib\site-packages\ipykernel\eventloops.py:256: RuntimeWarning: coroutine 'Kernel.do_one_iteration' was never awaited
  self.func()
C:\Users\adity\miniconda3\envs\Streamlit-Dev\lib\site-packages\ipykernel\eventloops.py:256: RuntimeWarning: coroutine 'Kernel.do_one_iteration' was never awaited
  self.func()


In [4]:
x.shape

(2000,)

In [5]:
z=np.arange(10)

In [7]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
z[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [37]:
za=np.pad(z,(len(z)-1,0),'constant')

In [38]:
za

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
zb=za[:len(z)*2]

In [40]:
zb

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:

import numpy as np
ab=np.lib.stride_tricks.sliding_window_view(zb,len(z))

In [46]:
ab

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 1, 2, 3],
       [0, 0, 0, 0, 0, 0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0, 1, 2, 3, 4, 5],
       [0, 0, 0, 0, 1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 2, 3, 4, 5, 6, 7],
       [0, 0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
af= np.arange(10)

In [50]:
np.pad(af,(len(af),0),'reflect')

array([8, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a = np.arange(10)
b= np.ones((10,5))

In [56]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.dot(a,b)

array([45., 45., 45., 45., 45.])

In [9]:
import numpy as np
a = np.arange(1,20)

In [10]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [1]:
from IPython.display import Audio

In [1]:
import streamlit-webrtc

SyntaxError: invalid syntax (Temp/ipykernel_11440/2535478197.py, line 1)