In [2]:
import streamlit as st
import numpy as np

2021-09-16 14:33:33.131 INFO    numexpr.utils: NumExpr defaulting to 4 threads.


In [2]:
class Input:
    

2021-09-16 09:14:14.096 
  command:

    streamlit run C:\Users\adity\anaconda3\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]


In [4]:
class Main:
    def __init__(self):
        pass

    def main(self):
        data1, data2 = file_loader(test.txt, test.txt)
        st.write(data1)
    @st.cache
    def file_loader(self, path1, path2):
        data1 = np.loadtxt(path1)
        data2 = np.loadtxt(path2)
        return data1, data2


In [5]:
data= np.loadtxt('test.txt')

In [12]:
import os,sys
os.path.dirname(r"test.txt")

''

In [13]:
start = os.path.dirname(sys.argv[0])
path = 'test.txt' 
relative_path = os.path.relpath(path, start)

In [14]:
relative_path

'..\\..\\..\\OneDrive - Institut Teknologi Sepuluh Nopember\\Kuliah\\Semester 5\\Biomod\\Program\\Program 1 Cross Corelation\\test.txt'

In [109]:
N= 10
m = np.array(range(N))
n= 9

print(m,(m+n)%N)

[0 1 2 3 4 5 6 7 8 9] [9 0 1 2 3 4 5 6 7 8]


In [91]:
np.correlate([1,2,3,4],[6,5,4,3,2,1],'full')

array([ 1,  4, 10, 20, 30, 40, 43, 38, 24])

ek eb jumlah b min(a,b)/2+1

ek ob jumlah b min(a,b)/2+1

kalau lebih kecil a dan genap

eb ek jumlah b min(a,b)/2

ob ek jumlah b (min(a,b))/2
e e
kalau lebih kecil b genap


ok ob jumlah b (min(a,b)+1)/2

ob ok jumlah b (min(a,b)+1)/2

eb ok jumlah b (min(a,b)+1)/2

ok eb jumlah b (min(a,b)+1)/2
o o a+1/2

min(a,b) ganjil (min(a,b)+1)/2


In [114]:
np.correlate(np.random.rand(7000),np.random.rand(7000),'full')

array([0.46465051, 0.50945871, 1.27377403, ..., 0.67900771, 0.2815631 ,
       0.01549876])

In [118]:
np.lib.stride_tricks.sliding_window_view(np.random.rand(14000),7000)

array([[0.61982981, 0.58166259, 0.55927183, ..., 0.90061215, 0.57222432,
        0.99985377],
       [0.58166259, 0.55927183, 0.98005705, ..., 0.57222432, 0.99985377,
        0.82629901],
       [0.55927183, 0.98005705, 0.9871375 , ..., 0.99985377, 0.82629901,
        0.7524015 ],
       ...,
       [0.57222432, 0.99985377, 0.82629901, ..., 0.86086415, 0.12112952,
        0.83899589],
       [0.99985377, 0.82629901, 0.7524015 , ..., 0.12112952, 0.83899589,
        0.34488713],
       [0.82629901, 0.7524015 , 0.39198667, ..., 0.83899589, 0.34488713,
        0.34717619]])

In [120]:
a= np.array([[1,2],[3,4]])
np.dot(a,np.array([1,2]))

array([ 5, 11])

In [130]:
a= np.arange(5)
b=np.pad(a,(len(a),len(a)),'constant',constant_values=99)
b

array([99, 99, 99, 99, 99,  0,  1,  2,  3,  4, 99, 99, 99, 99, 99])

In [131]:
b[0:len(a)]

array([99, 99, 99, 99, 99])

In [143]:
x=-1
b[len(a)-x:2*len(a)-x+3]

array([ 1,  2,  3,  4, 99, 99, 99, 99])

In [144]:
root = os.path.dirname(sys.argv[0])
path1 = r'Data\test.txt'
path2 = r'Data\test2.txt'

full_path1 = os.path.join(root, path1)
full_path2 = os.path.join(root, path2)

data1 = np.loadtxt(path1)
data2 = np.loadtxt(path2)

OSError: C:\Users\adity\anaconda3\lib\site-packages\Data\test.txt not found.

In [ ]:
np.cor